### ISSUE TITLE
How can i find the time of detection?

### ISSUE THREAD

**Issue by jaskiratsingh2000** [methylDragon/opencv-motion-detector#1]
Hey @methylDragon , I want to measure the time of detection that how much time does it take to detect anything. How can I do that?

**Comment by methylDragon** [comment]
Sorry, I don't understand the question?

**Comment by jaskiratsingh2000** [comment]
@methylDragon Oh what I mean to say is that How can I find the time it takes for the first detection and then the time taken to go from one frame to another

**Comment by methylDragon** [comment]
You'll likely have to independently track the timestamps of your images.

This implementation just feeds in image frames with no concept of time (it actually just uses number of frames.) Hope that answers your question!

**Comment by jaskiratsingh2000** [comment]
Sorry I couldn't get you what you mean to say by timestamps feeding here?

**Comment by methylDragon** [comment]
You need to keep track of the time of each frame yourself (associate a timestamp to each frame), consider using a time.time() call

**Comment by jaskiratsingh2000** [comment]
Oh Okay, I get it. Would it be possible at your end to implement this
feature please?

**Comment by methylDragon** [comment]
You're welcome to send a PR, I'm not actively supporting this repo

Cheers!
