### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by jayu9493** [methylDragon/opencv-motion-detector#2]
not enough values to unpack (expected 3, got 2).  
what is this error, Using in windows ...... any help would be appreciated...

**Comment by methylDragon** [comment]
You likely have an issue with your camera. Maybe you're using a non RGB camera? Unsure.

**Comment by qnihat** [comment]
cnts, _ = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

just remove the first variable.
